# Generated by Django 4.2.5 on 2023-09-22 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('iconUrl', models.TextField()),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('bannerUrl', models.TextField()),
            ],
            options={
                'db_table': 'Food',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snappApi.city')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='ShopsFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('rank', models.FloatField(max_length=50)),
                ('bannerUrl', models.TextField()),
                ('iconUrl', models.TextField()),
                ('Foods', models.ManyToManyField(to='snappApi.food')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snappApi.category')),
            ],
            options={
                'db_table': 'ShopsFood',
            },
        ),
    ]
