# Generated by Django 4.2.5 on 2023-09-24 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snappApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsfood',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='snappApi.city'),
        ),
    ]
